#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/yura/.Xmodmap"

setxkbmap -layout us,ru \
-option \
grp:menu_toggle,\
grp_led:scroll,\
terminate:ctrl_alt_bksp,\
ctrl:nocaps

#grp:menu_toggle       Menu key changes group.
#ctrl:nocaps caps key works as ctrlw

#setxkbmap -option 'ctrl:nocaps'
xset r rate 400 35 # cursor speed

~/.dropbox-dist/dropboxd &
nm-applet & # network manager applet

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/yura/.fluxbox/log"
